# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  

steps:
- task: UsePythonVersion@0
  inputs:
   versionSpec: '3.x'
   addToPath: true
  displayName: 'use python 3.x'
  
- script:|
  #install dependencies and build your application
  #pip install -r requirements.txt
  python setup.py build
  displayName: 'Build'

- script: |
    # run your tests
    pytest
  displayName: 'Run tests'

